// <auto-generated />
namespace GMCC.Sorter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GMCC_CommOptimize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GMCC_CommOptimize));
        
        string IMigrationMetadata.Id
        {
            get { return "201907290751046_GMCC_CommOptimize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
