// <auto-generated />
namespace Arthur.App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Arthur_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Arthur_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201905190944388_Arthur_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
